import Head from "next/head";
import Image from "next/image";
// @ts-ignore
import styles from "../styles/Home.module.css";
import { Suspense, useEffect } from "react";
import Spinner from "../components/spinner";
import PostList from "../components/post-list";
import { useAsyncResource } from "use-async-resource";
import { getPosts } from "./api/redditApi";

export default function Home() {
  const [postReader, getNewPosts] = useAsyncResource(getPosts, []);

  useEffect(() => {
    getNewPosts();
  }, [getNewPosts]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Reddit posts query test</h1>
        <Suspense fallback={<Spinner />}>
          <PostList postReader={postReader} />
        </Suspense>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
